name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  flutter_background: ^1.1.0
  permission_handler: ^11.3.1
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.5
  http: ^1.1.0
  dropdown_button2: ^2.3.6
  flutter_window_close: ^1.0.0
  collection: '>=1.16.0'
  chopper: ^8.0.0
  json_annotation: ^4.8.0

  livekit_client:
    path: ../
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
